### ISSUE TITLE
Project does not build in VisualStudio 2017 15.9.9

### ISSUE THREAD

**Issue by iraytrace** [KhronosGroup/UnityGLTF#382]
Building with VisualStudio 2017 15.9.9 succeeds in Debug build, but switching from Debug to Release build type with "Any CPU" selected results in two errors:

`
1>------ Rebuild All started: Project: Assembly-CSharp, Configuration: Release Any CPU ------
1>D:\Shared\Unity\UnityGLTF\UnityGLTF\Assets\UnityGLTF\Scripts\GLTFSceneImporter.cs(244,68,244,79): error CS1061: 'Task' does not contain a definition for 'AsCoroutine' and no accessible extension method 'AsCoroutine' accepting a first argument of type 'Task' could be found (are you missing a using directive or an assembly reference?)
1>D:\Shared\Unity\UnityGLTF\UnityGLTF\Assets\UnityGLTF\Examples\VisualizeMeshAttributes.cs(7,39,7,43): warning CS0649: Field 'VisualizeMeshAttributes.Mesh' is never assigned to, and will always have its default value null
2>------ Rebuild All started: Project: Assembly-CSharp-Editor, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file 'D:\Shared\Unity\UnityGLTF\UnityGLTF\Temp\bin\Release\Assembly-CSharp.dll' could not be found
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========
`

**Comment by iraytrace** [comment]
User Error.  GLTFSerialization is the proper project to open
