### ISSUE TITLE
CS0118 'Editor' is a namespace but is used like a type after updating to 2.16.0-pre.3

### ISSUE THREAD

**Issue by CharlieHess** [KhronosGroup/UnityGLTF#848]
### Describe the bug 💬

After encountering https://github.com/KhronosGroup/UnityGLTF/issues/820 on Unity6, I upgraded to 2.16.0-pre.3. This solved the import problem but created a bunch of new compilation errors, weirdly in many of my editor files.

The errors were all:

```
CS0118 'Editor' is a namespace but is used like a type
```
 
I haven't dug through exactly what changed in that release (or if it is that most recent version), but I can isolate the errors to the version bump from `2.14.1` to `2.16.0-pre.3`.

### Steps to reproduce 🔢

1. Start a clean slate project and add the latest version of the Khronos importer
2. Add any file that inherits from `UnityEditor.Editor`, as follows:

``` cs
using UnityEditor;
using UnityEngine;

public class LiterallyAnyEditor : Editor {

[...]
``` 
3. `CS0118 'Editor' is a namespace but is used like a type`

### Editor Version 🎲

6000.0

### Render Pipeline and version

URP 17

### UnityGLTF Version

2.16.0-pre.3

### Operating System 👩‍💻

macOS

### When does this problem happen?

- [ ] Editor Import
- [ ] Runtime Import
- [ ] Editor Export
- [ ] Runtime Export

### Validations 🩹

- [x] I have [searched existing issues](https://github.com/KhronosGroup/UnityGLTF/issues): no issue already exist that reports the same problem.
- [x] I follow the [Code of Conduct](https://www.khronos.org/about/code-of-conduct)
- [x] I provided a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), including files when necessary.

**Comment by marwie** [comment]
Looks like this namespace is wrong 

https://github.com/KhronosGroup/UnityGLTF/blob/4da23d4f010d1bbdfec0e024bb9f2758516ecf5f/Editor/Scripts/Interactivity/VisualScriptingExport/UnitExporters/GltfInteractivityUnits/GltfLogUnitExporter.cs#L8

**Comment by CharlieHess** [comment]
> Looks like this namespace is wrong
> 
> [UnityGLTF/Editor/Scripts/Interactivity/VisualScriptingExport/UnitExporters/GltfInteractivityUnits/GltfLogUnitExporter.cs](https://github.com/KhronosGroup/UnityGLTF/blob/4da23d4f010d1bbdfec0e024bb9f2758516ecf5f/Editor/Scripts/Interactivity/VisualScriptingExport/UnitExporters/GltfInteractivityUnits/GltfLogUnitExporter.cs#L8)
> 
> Line 8 in [4da23d4](/KhronosGroup/UnityGLTF/commit/4da23d4f010d1bbdfec0e024bb9f2758516ecf5f)
> 
>  namespace Editor.UnitExporters.GltfInteractivityUnits

Bingo, same thing happened to ProBuilder [a while back](https://issuetracker.unity3d.com/issues/error-cs0118-editor-is-a-namespace-but-is-used-like-a-type-error-is-thrown-when-using-unityeditor-dot-editor-for-a-custom-inspector)

**Comment by pfcDorn** [comment]
Hey, thanks for the issue! 
I fixed it and a new prerelease should be soon available (Version 2.16.0-pre.4)
