### ISSUE TITLE
UWP shader errors with Unity 2017.4.3 / 2018.1.2

### ISSUE THREAD

**Issue by deadlyfingers** [KhronosGroup/UnityGLTF#187]
Cannot play example scene in Unity 2018.1.2f1 - getting shader errors:

`Shader error in 'GLTF/PbrMetallicRoughness': invalid subscript 'uv2' at /Applications/Unity/Unity.app/Contents/CGIncludes/UnityStandardMeta.cginc(21) (on metal)`

`Shader error in 'GLTF/PbrSpecularGlossiness': invalid subscript 'uv2' at /Applications/Unity/Unity.app/Contents/CGIncludes/UnityStandardMeta.cginc(21) (on metal)`

**Comment by deadlyfingers** [comment]
Ah these errors disappear once you build the GLTFSerialization.dll Plugins!

But now you get these compiler errors:
`Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/PlatformRunner/PlatformRunner.cs(93,16): error CS1502: The best overloaded method match for `string.IsNullOrEmpty(string)' has some invalid arguments`

Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/PlatformRunner/PlatformRunner.cs(93,30): error CS1503: Argument `#1' cannot convert `UnityEditor.Build.Reporting.BuildReport' expression to type `string'

**Comment by deadlyfingers** [comment]
While it builds ok in Unity 2108.1.2 (didn't build using older version of Unity 2017) you get the following "ShaderNotFoundException" error.
<img width="486" alt="gltf-uwp-error" src="https://user-images.githubusercontent.com/1880480/40967458-edeec11e-68aa-11e8-8485-665c1e926cba.PNG">

**Comment by deadlyfingers** [comment]
Is it possible to avoid the build step for GLTFSerialization.dll?
I made a fork of the repo and and it seems to work as scripts with some minor changes:  
https://github.com/deadlyfingers/UnityGLTF/tree/unity2017-uwp/UnityGLTF/Assets/UnityGLTF/GLTFSerialization

**Comment by peted70** [comment]
I think the GLTF shaders need to be moved into the Resources folder as they are not referenced by anything in the test scenes and as a result don't get added to the appx. The code loads them using Shader.Find so they either need to be referenced by a material in use or by adding to Resources folder which will include them automatically or an equivalent. (I tried adding to the ''Always Include' list in Player > Graphics but this resulted in a hang using Unity 2017.4.3f1).
